#!/usr/bin/python3

"""
    This module is created to return the
    factors of a number in the format
    n=p*q. With processing speed as a
    critical factor
    """
import sys


def reading(file):
    """
    A function to handle file opening and closing.
    """
    with open(file) as data:
        new_data = data.readlines()
        # print(new_data)
    return new_data


def factorize(value):
    """"Prints out factorials of value in the
    value(n)=p*q format. Where p & q are
    factorials of the value n.
    """
    i = 2

    if value < 2:
        return

    while value % i:
        i += 1

    print(f"{value}={(value/i):.0f}*{i}")


def main():
    try:
        data = reading(sys.argv[1])
        for item in data:
            value = int(item)
            factorize(value)

    except Exception as err:
        print(err)


"""start Main Function"""
main()
