#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
In the shortest possible time. Program will be killed after 5 seconds
    Usage: python3 rsa <file>
    Output format: n=p*q

"""
# library to get arguments
import sys


def reading(file):
    """
    A function to handle file opening and closing.
    """
    with open(file) as data:
        new_data = data.readlines()
    return new_data


def factorize():
    """"Prints out factorials of value in the
    value(n)=p*q format. Where p & q are
    factorials of the value n.
    """
    try:
        for file_index in range(len(sys.argv)):
            if file_index != 0:
                data = reading(sys.argv[file_index])
                for item in data:
                    value = int(item)
                    if value % 2 == 0:
                        print(f"{value}={value//2}*{2}")
                        continue
                    i = 3
                    while i < value // 2:
                        if value % i == 0:
                            print(f"{value}={value//i}*{i}")
                            break
                        i = i + 2

                    if i == (value // 2) + 1:
                        print(f"{value}={value}*{1}")

    except Exception as err:
        print(err)


# start
factorize()
